name: Create GitHub Pages Branch

on:
  push:
    branches:
      - master

jobs:
  create_github_pages_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "cuentafrst@gmail.com"
          git config --global user.name "Armando"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.7

      - name: Install dependencies
        run: pnpm install

      - name: Build app project
        run: |
          pnpm build
          find . -name "node_modules" -type d -prune -exec rm -rf {} +

      - name: Create GitHub Pages Branch
        run: |
          git checkout -b gh-pages
          git rm -rf .
          rsync -av dist/ .
          rm -rf dist
          git add .
          git commit -m "Build static site."

      - name: Push GitHub Pages Branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
